### ISSUE TITLE
Internal error  An error occurred on the page you were trying to access.

### ISSUE THREAD

**Issue by ghost** [integra-consultores/meetings#4]
Hi,

I am getting internal error when i try to go to meeting tab. I am on redmine version 2.3.0.stable. This is what i got in my production log.

Started GET "/projects/my-project-internal/meetings" for 192.168.6.180 at 2013-05-02 11:22:11 -0500
Processing by MeetingsController#index as HTML
  Parameters: {"project_id"=>"my-project-internal"}
  Current user: user.name (id=3)
Completed 500 Internal Server Error in 86ms

NoMethodError (undefined method `each' for nil:NilClass):
  app/models/query.rb:310:in`available_filters'

Is there anything i am missing?

**Comment by KappaNossi** [comment]
Got the same error, also on 2.3.0 stable

However, I can only get even this far only when debugging. When running normally (on production or development env) MeetingQueriesHelper already cannot find the class 'MeetingQuery'. Don't know why it gets past this point in Debug mode though.

```
NameError (uninitialized constant MeetingQueriesHelper::MeetingQuery):
  plugins/meetings/app/helpers/meeting_queries_helper.rb:14:in `retrieve_query'
  plugins/meetings/app/controllers/meetings_controller.rb:96:in `index'
  actionpack (3.2.13) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
```

When running in debug mode, I get the error of the OP. Stack trace suggests that he also cannot find the MeetingQuery class properly as he's entering the Query method instead of the MeetingQuery one, which overrides it. The calling Object when inside the 'available_filters' method really is of type MeetingQuery though...

May I also suggest rewriting your method to conform to other Query subclasses which only override the 'initialize_available_filters' if it's not too much trouble.

**Comment by bishma-stornelli** [comment]
I hope to be working on this next week. I've been a little busy lately.

**Comment by angra1982** [comment]
I have the same error. :(

**Comment by Drako** [comment]
So? any updates on this issue? Two months later and now I get that error :/

**Comment by codyliou** [comment]
I have the same error

Started GET "/projects/test/meetings" for 127.0.0.1 at 2013-08-16 16:46:15 +0800
Processing by MeetingsController#index as HTML
  Parameters: {"project_id"=>"test"}
  Current user: admin (id=1)
Completed 500 Internal Server Error in 18ms

NoMethodError (undefined method `[]=' for nil:NilClass):
  plugins/meetings/app/models/meeting_query.rb:8:in`initialize'
  plugins/meetings/app/helpers/meeting_queries_helper.rb:14:in `new'
  plugins/meetings/app/helpers/meeting_queries_helper.rb:14:in`retrieve_query'
  plugins/meetings/app/controllers/meetings_controller.rb:96:in `index'

**Comment by zalesak** [comment]
Here is patch for redmine 2.4.x
https://drive.google.com/file/d/0B3Ppsx6owKtjeXNEM2t6ekJtSTA/edit?usp=sharing

**Comment by undigo** [comment]
the patch from zelesak is ok for my configuration
Environment:
  Redmine version                          2.3.0.stable
  Ruby version                             1.9.3 (x86_64-linux)
  Rails version                            3.2.13
  Environment                              production
  Database adapter                         Mysql2
Redmine plugins:
  a_common_libs                            0.0.1
  clipboard_image_paste                    1.8
  holidays                                 0.1.0
  meetings                                 0.0.2
  recurring_tasks                          1.2.9
  redcase                                  1.0 beta 2.0
  redmine_advanced_issues                  0.0.5
  redmine_appmenuadds                      1.4.1
  redmine_backlogs                         v0.9.38
  redmine_charts2                          0.2.1
  redmine_ckeditor                         1.0.15
  redmine_didyoumean                       1.2.0
  redmine_dmsf                             1.4.5 stable
  redmine_drafts                           0.2.0
  redmine_easy_edit                        0.0.6
  redmine_email_notification_content_filter 0.0.2
  redmine_improved_searchbox               0.0.3
  redmine_issue_checklist                  2.0.5
  redmine_issue_history_tabs               0.0.3
  redmine_issue_templates                  0.0.6
  redmine_knowledgebase                    3.0.0
  redmine_logs                             0.0.5
  redmine_questions                        0.0.5
  redmine_reminder                         0.4
  redmine_sidebar_toc                      0.0.1
  redmine_stealth                          0.6.0
  redmine_time_tracker                     0.0.1
  redmine_traceability                     2.1
  redmine_track_control                    1.0.8
  redmine_wiki_backlinks                   0.0.2
  redmine_wiki_extensions                  0.6.4
  redmine_work_time                        0.2.11
  rougemine                                1.0.3
  status_button                            0.1.0

**Comment by igor-panassiouk** [comment]
Unfortunstely patch from @zalesak didn't help my Redmine 2.3.0 stable installation

Here is part of production .log:

DEPRECATION WARNING: The InstanceMethods module inside ActiveSupport::Concern will be no longer included automatically. Please define instance methods directly in Kaminari::ActiveRecordModelExtension instead. (called from <top (required)> at /var/www/redmine-2.3.0/plugins/meetings/app/models/meeting.rb:1)
DEPRECATION WARNING: The InstanceMethods module inside ActiveSupport::Concern will be no longer included automatically. Please define instance methods directly in Kaminari::ConfigurationMethods instead. (called from <top (required)> at /var/www/redmine-2.3.0/plugins/meetings/app/models/meeting.rb:1)
DEPRECATION WARNING: Paginator no longer takes a controller instance as the first argument. Remove it from #new arguments. (called from initialize at /var/www/redmine-2.3.0/lib/redmine/pagination.rb:28)
DEPRECATION WARNING: Paginator#current will be removed. Use .offset instead of .current.offset. (called from current at /var/www/redmine-2.3.0/lib/redmine/pagination.rb:99)
DEPRECATION WARNING: The InstanceMethods module inside ActiveSupport::Concern will be no longer included automatically. Please define instance methods directly in #Module:0x00000002ed28b0 instead. (called from realtime at /usr/lib/ruby/1.9.1/benchmark.rb:295)
  Rendered queries/_filters.html.erb (16.9ms)
  Rendered queries/_columns.html.erb (174.8ms)
  Rendered plugins/meetings/app/views/meetings/index.html.erb within layouts/base (237.5ms)
Completed 500 Internal Server Error in 607ms

ActionView::Template::Error (undefined local variable or method `tag_name' for #<#<Class:0x00000007c2ccf0>:0x00000007bab8a8>):
    17:     <td>
    18:       <%= label_tag "selected_columns", l(:description_selected_columns) %>
    19:       <br />
    20:       <%= select_tag tag_name,
    21:               options_for_select(query_selected_inline_columns_options(query)),
    22:               :id => 'selected_columns', :multiple => true, :size => 10, :style => "width:150px",
    23:               :ondblclick => "moveOptions(this.form.selected_columns, this.form.available_columns);" %>
  app/views/queries/_columns.html.erb:20:in`_24c05542c0e1ea7a78964417e81420b0'
